name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ARM64

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --platform=linux/arm64 . --file .\TelegramMultiBot\Dockerfile --tag bober-bot:$(date +%s)
