name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Create new tag (bump patch)
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          default_bump: patch

  build:
    runs-on: ubuntu-24.04-arm
    needs: tag
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./TelegramMultiBot/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            bober-bot:${{ needs.tag.outputs.new_tag }}
            bober-bot:latest
